### ISSUE TITLE
Color selector for character creation doesn't work.

### ISSUE THREAD

**Issue by BurgerLUA** [TheSwain/Fulpstation#227]
Happens every round I've tried it on. Bascially if you try to set a custom color for underwear or the lizard race skintone, it defaults to black regardless of selection. Doesn't seem to happen on other /tg/ servers so I think it's exclusive to this base.

**Comment by boodaliboo** [comment]
lol

**Comment by remove32** [comment]
our revision is a few days old, newer tg code will probably fix this

**Comment by BurgerLUA** [comment]
This was fixed in a recent update.
