### ISSUE TITLE
the departmental borg keys that borgs now get when they select a module eat other keys

### ISSUE THREAD

**Issue by ATH1909** [TheSwain/Fulpstation#241]
If you put a captain's encryption key in a cyborg, then have that cyborg choose, say, the medical module, they'll ONLY have access to the medical comms channel. The captain's encryption key that you put in them will be both unusable by the cyborg completely unrecoverable, even if you deconstruct the entire borg.

If you have a cyborg choose a module, then put a captain's encryption key in them, the captain's encryption key will have no effect (and also be unrecoverable). In other words, the order that you put the key in the borg and have the borg choose any module doesn't matter, they're still not gonna be able to use their non-module default headset key.

If you detonate a non-emagged cyborg that has chosen a module, they'll drop their chosen module's default encryption key (a medical one for medical cyborgs, for example).

https://github.com/TheSwain/Fulpstation/pull/196 is that cause of this, I believe. I recommend reverting it, as it was a good but poorly executed idea.

**Comment by ATH1909** [comment]
@Surrealaser

**Comment by Surrealaser** [comment]
@ATH1909 As I mentioned to you previously, I'm aware of this and am considering changes.

Also, it is notable that a borg getting a captain encryption key before choosing a module is super niche.

**Comment by ATH1909** [comment]
> @ATH1909 As I mentioned to you previously, I'm aware of this and am considering changes.
> 
> Also, it is notable that a borg getting a captain encryption key before choosing a module is super niche.

I sometimes choose my module after I see how competent the roboticists are. If they're new, I'll go standard, but if I can trust them to repair and upgrade me quickly and efficiently, I'll go secborg.

Also, what about my second point? If you choose a module first, THEN receive a key, the "external" key STILL gets deleted.

**Comment by Surrealaser** [comment]
@ATH1909 

This is fixed per the following PR:

https://github.com/TheSwain/Fulpstation/pull/242

Again, these concerns are generally niche and most certainly do not merit a revert, but I don't see the harm in addressing them.

**Comment by Surrealaser** [comment]
@ATH1909 Close this.

**Comment by remove32** [comment]
fixeroni'd by #242
