### ISSUE TITLE
mesmerize doesn't work on (most) plasmamen

### ISSUE THREAD

**Issue by ATH1909** [TheSwain/Fulpstation#246]
```
	// Check: Target has eyes?
	if (!target.getorganslot("heart"))
		if (display_error)
			to_chat(owner, "<span class='warning'>They have no eyes!</span>")
		return FALSE
```
Whenever the Mesmerize vampire ability tries to check to see if the target still has eyes, it _actually_ checks to see if the target still has a _heart_. Since plasmamen don't start the round with/need hearts, unless that plasmaman has gotten a heart surgically implanted into them or something, they're gonna be immune to your Mesmerize power.

**Comment by AtlasRules** [comment]
why would it target the heart lmao, that makes no sense.

**Comment by ATH1909** [comment]
> why would it target the heart lmao, that makes no sense.

It was probably copy+pasted from somewhere else and a coder forgot to change it to check for eyes instead of a heart.

**Comment by remove32** [comment]
lmao this is pretty funny
