### ISSUE TITLE
the emitters in the gauntlet away mission don't fire by default

### ISSUE THREAD

**Issue by ATH1909** [TheSwain/Fulpstation#262]
For whatever reason, the many emitters in the gauntlet away mission... aren't firing. I dunno if you can turn them on (I was a borg and didn't bother interacting with them directly), but from what I can tell from my codediving, they're supposed to start on.

Also, you should set the accelerator laser turrets to attack borgs by default, because they completely ignored me as a borg, allowing me to just walk up to them and bash 'em down.

Does this away mission originate from fulpstation or from /tg/? If it's from /tg/, it might be better to fix it upstream instead of only in this downstream.

**Comment by gonenoculer5** [comment]
@ATH1909 All (current) gateway missions as of 2/20/2020 originate from upstream. This is a bug that should be reported upstream to TG directly instead of our issue tracker, thank you.

**Comment by gonenoculer5** [comment]
@remove32 Can we close this and give it the upstream tag? (If we have one)

**Comment by remove32** [comment]
upstream - please report there
