### ISSUE TITLE
HoP's monitor can view security body cameras

### ISSUE THREAD

**Issue by Shadowtail117** [TheSwain/Fulpstation#266]
![Capture123](https://user-images.githubusercontent.com/25853190/74484443-6c15ef00-4e6d-11ea-83a0-68e077e78e63.PNG)

I doubt this is intentional. I wanted to give a heads up. Since he made the PR, @Surrealaser.

**Comment by Shadowtail117** [comment]
This happens to the interrogation room monitor as well. Not sure about other ones yet.

**Comment by Surrealaser** [comment]
@Shadowtail117 If you have security access, it is completely intentional. People with security access can tap any kind of monitor to spot through body cams.

**Comment by Shadowtail117** [comment]
Ah, I see. Not a bug then. Thanks for the clarification.
