### ISSUE TITLE
budget emags can't emag already emagged borgs

### ISSUE THREAD

**Issue by ATH1909** [TheSwain/Fulpstation#294]
@Surrealaser

This is because check_emag_status() returns true if the cyborg you're trying to budget emag has already been emagged, even if they've been emagged by someone else and you're trying to subvert them to yourself instead.

**Comment by ATH1909** [comment]
Also, Cale on Discord reported that a non-emagged borg (who wasn't slaved to a malf AI) was unable to be budget emagged by him. No, his budget emag was not out of charges; he chainflashed the borg specifically so that he could give his budget emag time to recharge.

Also, from looking at the code, it looks like unlocking an emagged borg's cover won't deduct a charge (and can be done when you're out of emag charges), and the reduction in charge for emagging a borg will be delayed for a few seconds after you emag it, allowing you to emag another item or two in the mean time.

**Comment by ATH1909** [comment]
Also, it looks like a borg with an illegal equipment upgrade is also un-budget emaggable.

**Comment by Surrealaser** [comment]
@ATH1909 Should be fixed: https://github.com/TheSwain/Fulpstation/pull/295
