### ISSUE TITLE
Just a minot implementation of Mourning Poultice for chemistry/botany

### ISSUE THREAD

**Issue by PotatoWarrior** [TheSwain/Fulpstation#517]
TG has updated their chemistry not sure for how long but they added this neat little thing that heals damage on dead bodies witch would really give botany another thing to work towards, not to mention that healing dead bodies might be made faster and more enjoyable.

**Comment by remove32** [comment]
in the works is a rebase on tg. i'll be putting an announcement in the forum and discord regarding that once we're in a working state on the new repo
