### ISSUE TITLE
Split Personality swapping is broken

### ISSUE THREAD

**Issue by ModDownloading** [TheSwain/Fulpstation#520]
Fulpstation is using older, unfixed code for the Split Personality trauma, so the second personality never actually switches into the body. TG fixed this with a one-line change PR (PR #54610) and I think it should be fixed over on Fulp as well so Split Personality can actually work as intended.

Steps:
1. Get split personality trauma
2. Have someone else be the split personality
3. Notice the split personality never takes over the body, regardless of how long you wait

**Comment by remove32** [comment]
we're in the progress of moving to the [new repo ](https://github.com/fulpstation/fulpstation)at the moment. I won't be fixing this in this repo as the plan is to archive it.

thanks for reporting it though
